### ISSUE TITLE
NullReferenceException

### ISSUE THREAD

**Issue by TobyKaos** [xtralifecloud/unity-sdk#12]
Sans rien faire j'ai souvent cette erreur dans Xcode.

NullReferenceException: A null value was found where an object instance was required.
  at CotcSdk.UnityHttpClientV2+UnityRequest+<ProcessRequest>d__8.MoveNext () [0x00000] in <filename unknown>:0 
  at UnityEngine.SetupCoroutine.InvokeMoveNext (IEnumerator enumerator, IntPtr returnValueAddress) [0x00000] in <filename unknown>:0

**Comment by TobyKaos** [comment]
Je vais checker si ce n'est pas dans mon code lorsque j'empile des appels de fonctions qui appel justement les fonctions xtralife

**Comment by TobyKaos** [comment]
j'ai testé avec une app de test.

Test fait:
lancement de l'app sur IOS avec Xcode 8.2.1
Unity 5.5.0p4
Xtralife 1.1.2.3

Au lancement appuie sur home puis revient dans l'app. Pas d'erreur.

Après un login anonyme refait la même manip et là j'ai l'erreur NullReferenceException

A noter que dans ce cas on ne reçoit plus les Events.

Surement est-ce lié.

**Comment by MikeoftheClan** [comment]
There was indeed a bug, due to a Unity bug with UnityWebRequest on iOS, as described here:
https://issuetracker.unity3d.com/issues/ios-unitywebrequest-dot-error-is-not-set-after-abort-is-called-on-ios

Aborting a request does not actually abort it. We now process this special case so it won't happen anymore.
